.gitignore, docs/extensions/offline-react-native.md, docs/extensions/offline-web.md, package.json
Also update the version number
Also fix the import statement in the offline-web docs
=> Fix errors in the build process

README.md, src/targets/amplitude/amplitude.js, src/targets/amplitude/index.d.ts, src/targets/amplitude/index.js, test/targets/amplitude.js
Amplitude support...kind of a big deal for a few projects. Let me know if you want this to live elsewhere as a separate package and maintained outside the core lib.
=> Add Amplitude target

index.d.ts
=> Remove forbidden trailing comma in typings

examples/google-analytics/index.js
=> Add offline event sync to example app

README.md
=> Add pitch for offline event collection

package.json, src/extensions/logger/__tests__/logger.test.js, src/extensions/offline-react-native/__tests__/offline-react-native.test.js, src/extensions/offline-web/__tests__/offline-web.test.js, src/main/__tests__/create-events.test.js, src/main/__tests__/create-meta-reducer.test.js, src/main/__tests__/create-middleware.test.js, src/targets/amplitude/__tests__/amplitude.test.js, src/targets/cordova-google-analytics/__tests__/cordova-google-analytics.test.js, src/targets/google-analytics/__tests__/google-analytics.node-env.test.js, src/targets/google-analytics/__tests__/google-analytics.test.js, src/targets/google-tag-manager/__tests__/google-tag-manager.node-env.test.js, src/targets/google-tag-manager/__tests__/google-tag-manager.test.js, src/targets/react-native/google-analytics/__tests__/google-analytics.test.js, src/targets/react-native/google-tag-manager/__tests__/google-tag-manager.test.js, src/targets/segment/__tests__/segment.test.js, yarn.lock
Facebook Jest uses this, I'm hoping it will be a lot simpler to set up than coveralls.
=> Add codecov

docs/targets/amplitude.md, docs/targets/cordova-google-analytics.md, docs/targets/google-tag-manager.md, docs/targets/react-native-google-analytics.md, docs/targets/segment.md
=> Update target docs to use new event definitions

.babelrc, src/main/__tests__/create-events.test.js, src/main/__tests__/integration.test.js, src/main/__tests__/main.types.test.js, src/main/__tests__/register-events.test.js, src/main/create-events.js, src/main/create-meta-reducer.js, src/main/create-middleware.js, src/main/index.js, src/main/register-events.js, test/api.js, yarn.lock
=> Update main lib to use ES2015 modules

docs/targets/google-analytics.md, src/targets/google-analytics/__tests__/google-analytics.test.js, src/targets/google-analytics/google-analytics.js, src/targets/google-analytics/index.d.ts, src/utils/__tests__/ga-ecomm-helpers.test.js, src/utils/ga-ecomm-helpers.js, src/utils/index.js
=> Add support in for google analytics eCommerce plugin

src/targets/google-analytics/__tests__/google-analytics.test.js, src/targets/google-analytics/google-analytics.js
2 talking points I have are:
1) Would an array of trackers for each event be desirable?
2) Taking the comments and backwards compatibility into consideration, I allowed for using customTrackerId or tracker. Not sure if it should have just been customTrackerId.
=> issue #129 multiple trackers

src/extensions/logger/logger.js
Console.group method is not supported in the production React-Native environment, a polyfill should solve this.
=> [147] Console.group React-Native issue

docs/targets/react-native-google-analytics.md, src/targets/react-native/google-analytics/google-analytics.js
This just adds documentation on how to take advantage of the new hit types added by @djw27 in their PR. 
@ttmarek forked off of @djw27's project. Not sure if this is the what you were expecting. I can change the base of this fork if needed.
=> Add documentation for custom dimensions

lerna.json, package.json, yarn.lock
Checklist
----
What was done
----
----
:heart: Thanks
----
=> Remove lerna

packages/amplitude/package.json, packages/combine-events/package.json, packages/debounce-event/package.json, packages/ensure/package.json, packages/google-analytics-gtag/package.json, packages/google-analytics/package.json, packages/google-tag-manager/package.json, packages/logger/package.json, packages/offline-react-native/package.json, packages/offline-web/package.json, packages/react-native-google-analytics/package.json, packages/react-native-google-tag-manager/package.json, packages/redux-beacon/package.json, packages/segment/package.json
Checklist
----
What was done
----
----
:heart: Thanks
----
=> Add prepublish scrips to each package

packages/redux-beacon/src/__tests__/get-events-with-matching-key.test.ts, packages/redux-beacon/src/get-events-with-matching-key.ts
Checklist
----
What was done
----
----
:heart: Thanks
----
=> Fix regex matching eventsMap

docs/api/events-map.md, examples/ngrx-store/redux-beacon-ngrx-store.patch
Checklist
----
What was done
----
----
:heart: Thanks
----
=> Update ngrx-store example

.github/CONTRIBUTING.md
Checklist
----
What was done
----
----
:heart: Thanks
----
=> Update contributing doc

docs/getting-started-ngrx-users.md, docs/getting-started-redux-users.md
Checklist
----
What was done
----
----
:heart: Thanks
----
=> Update ngrx/store getting started page

docs/examples-and-recipes.md, docs/getting-started-ngrx-users.md
Checklist
----
What was done
----
----
:heart: Thanks
----
=> Add example: page views in Angular/ngrx/store

SUMMARY.md, docs/faq.md
Checklist
----
What was done
----
----
:heart: Thanks
----
=> Add FAQ page with AOT question

docs/examples-and-recipes.md
Checklist
----
What was done
----
----
:heart: Thanks
----
=> Add docs on how to create own target

docs/examples-and-recipes.md
Checklist
----
What was done
----
----
:heart: Thanks
----
=> Add example on sending analytics to multiple targets

docs/getting-started-ngrx-users.md, docs/getting-started-redux-users.md
Checklist
----
What was done
----
----
:heart: Thanks
----
=> Simplify getting started docs

docs/examples-and-recipes.md
Checklist
----
What was done
----
----
:heart: Thanks
----
=> Add example on tracking pageviews in React

README.md, docs/examples-and-recipes.md
Checklist
----
What was done
----
----
:heart: Thanks
----
=> Add packages section to readme

docs/examples-and-recipes.md, docs/getting-started-ngrx-users.md, docs/getting-started-redux-users.md, docs/targets/amplitude.md, docs/targets/google-analytics-gtag.md, docs/targets/google-analytics.md, docs/targets/google-tag-manager.md, docs/targets/react-native-google-analytics.md, docs/targets/react-native-google-tag-manager.md, docs/targets/segment.md, examples/ngrx-store/README.md
Checklist
----
What was done
----
----
:heart: Thanks
----
=> Update docs to work well with new gitbook

.gitbook.yaml
Checklist
----
What was done
----
----
:heart: Thanks
----
=> Try revised gitbook config for beta

docs/README.md, docs/SUMMARY.md, docs/api/create-meta-reducer.md, docs/migration-guide-v1-v2.md, examples/ngrx-store/README.md
Checklist
----
What was done
----
----
:heart: Thanks
----
=> Add migration guide v1 to v2

packages/redux-beacon/src/__tests__/integration.test.ts, packages/redux-beacon/src/create-meta-reducer.ts, packages/redux-beacon/src/create-middleware.ts, packages/redux-beacon/src/types.ts
Checklist
----
What was done
----
----
:heart: Thanks
----
=> Add test for events mapper and add to createMetaReducer

README.md
Checklist
----
What was done
----
----
:heart: Thanks
----
=> Update Github README

packages/redux-beacon/README.md, packages/redux-beacon/package.json
Checklist
----
What was done
----
----
:heart: Thanks
----
=> Publish v2

packages/google-analytics-gtag/package.json, packages/google-analytics-gtag/src/__tests__/google-analytics-gtag.test.ts, packages/google-analytics-gtag/src/google-analytics-gtag.ts
Checklist
----
What was done
----
----
:heart: Thanks
----
=> Update GA (gtag.js) to work with page view event-helper

packages/google-analytics-gtag/package.json
Checklist
----
What was done
----
----
:heart: Thanks
----
=> Publish fix GA (gtag.js) target

packages/debounce-event/README.md, packages/debounce-event/package.json
Checklist
----
What was done
----
----
:heart: Thanks
----### Example
```js
import debounceEvent from 'redux-beacon/utils/debounce-event';
// A normal event definition
const searchTerm = (action) => ({
hitType: 'event',
eventCategory: 'books',
eventAction: 'search',
eventLabel: action.payload
});
const eventsMap = {
// Assume that SEARCH_TERM_ENTERED fires whenever a user types a character into
// …
```
=> Give debounce-event a readme and publish again

packages/redux-beacon/package.json
Checklist
----
What was done
----
----
:heart: Thanks
----
=> Publish v2.0.3

docs/utils/debounce-event.md, docs/utils/ensure.md, packages/debounce-event/README.md, packages/debounce-event/package.json
Checklist
----
What was done
----
----
:heart: Thanks
----
=> Fix imports in docs

packages/google-analytics/src/event-helpers.ts
Checklist
----
What was done
----
----
:heart: Thanks
----
=> Fix GA event-helpers

docs/targets/google-analytics.md, packages/google-analytics/src/__tests__/google-analytics.test.ts, packages/google-analytics/src/event-helpers.ts, packages/google-analytics/src/google-analytics.ts
Checklist
----
What was done
----
----
:heart: Thanks
----
=> Update addAction to setAction

docs/faq.md
Checklist
----
What was done
----
I've updated the FAQ to reflect the fact that meta reducers are functions that take a `reducer` as a parameter instead of `state` and `action`.
----
#127 
:heart: Thanks
----
🤷‍♂️
=> Update Meta Reducer signature in FAQ

packages/offline-react-native/package.json
Checklist
----
What was done
----
----
:heart: Thanks
----
=> Publish offline-react-native v1.0.1

packages/amplitude/src/__tests__/amplitude.test.ts, packages/amplitude/src/amplitude.ts
Checklist
----
What was done
----
----
:heart: Thanks
----
=> Fix Amplitude target so it works without a global amplitude instance

docs/targets/amplitude.md
Checklist
----
What was done
----
- Change Amplitude target usage example to not use an instance name to avoid confusion 
----
- #268 
:heart: Thanks
----
=> Change Amplitude target docs

docs/utils/combine-events.md
Checklist
----
What was done
----
----
:heart: Thanks
----
=> Fix incorrect import statement in combine-events docs

docs/targets/google-tag-manager.md
Checklist
----
What was done
----
Documentation for google tag manager target modified
----
- https://github.com/rangle/redux-beacon/issues/273
=> Added doc about usage of google tag manager variables

packages/google-analytics/src/event-helpers.ts
Checklist
----
What was done
----
Fixed this issue: https://stackoverflow.com/questions/51634978/missing-required-field-timingcategory-and-timingvar-for-hit-of-type-ti
----
:heart: Thanks
----
=> Fix GA user timing event helper

package.json, packages/segment/src/__tests__/segment.test.ts, packages/segment/src/segment.ts, packages/segment/src/types.ts
Checklist
----
What was done
----
The implementation of the `track` method from the segment integration was not working as described in the documentation. As the whole event object was passed as the second parameter it didn't [match the signature of the official client](https://segment.com/docs/sources/website/analytics.js/#track) as it expected the un-nested properties. In addition `options` were omitted as a 3rd value. 
With this PR the method got updated to work with the service as described. In addition the `Traits` type definition was …
=> Fix segment track parameters

docs/targets/google-analytics.md, packages/google-analytics/src/__tests__/event-helpers.test.ts, packages/google-analytics/src/event-helpers.ts
Checklist
----
What was done
----
----
- Fixes #280 
:heart: Thanks
----
=> Update field validation for Google Analytics Enhanced Ecomm

packages/google-analytics/src/event-helpers.ts
Checklist
----
What was done
----
----
:heart: Thanks
----
=> change field names for trackException Issue #294

packages/redux-beacon/src/types.ts
What was done
----
Added generics to `EventDefinition` for Action and PrevState/NextState.
----
- #301
=> feat(EventDefinition): added generics for better types

scripts/publish.js
Checklist
----
What was done
----
----
:heart: Thanks
----
=> Add script for automated publishing

.circleci/config.yml
Checklist
----
What was done
----
----
:heart: Thanks
----
=> Add publish script to circle steps

packages/google-analytics/README.md
Checklist
----
What was done
----
----
:heart: Thanks
----
=> Give the Google Analytics target a README

.circleci/config.yml
Checklist
----
What was done
----
----
:heart: Thanks
----
=> Add npm auth step to circle config

packages/google-analytics-gtag/README.md
Checklist
----
What was done
----
----
:heart: Thanks
----
=> Give the Google Analytics (Gtag) target a readme

.circleci/config.yml, package.json, scripts/publish.js, yarn.lock
Checklist
----
What was done
----
----
:heart: Thanks
----
=> Update publish script

packages/amplitude/README.md
Checklist
----
What was done
----
----
:heart: Thanks
----
=> Add readme

scripts/publish.js
Checklist
----
What was done
----
----
:heart: Thanks
----
=> Set git user in publish script

packages/segment/README.md
Checklist
----
What was done
----
----
:heart: Thanks
----
=> Give the Segment target a readme

scripts/publish.js
Checklist
----
What was done
----
----
:heart: Thanks
----
=> Skip publish script in pr builds

packages/amplitude/package.json
Checklist
----
What was done
----
----
:heart: Thanks
----
=> Sync Amplitude package json with npm version

packages/google-analytics-gtag/src/__tests__/__snapshots__/google-analytics-gtag.test.ts.snap, packages/google-analytics-gtag/src/__tests__/google-analytics-gtag.test.ts, packages/google-analytics-gtag/src/google-analytics-gtag.ts
Checklist
----
What was done
----
----
@bertrandk
=> Fail gracefully when window.gtag is undefined

packages/google-analytics/src/__tests__/google-analytics.test.ts, packages/google-analytics/src/google-analytics.ts, packages/google-analytics/src/utils/__tests__/remove-keys.test.ts, packages/google-analytics/src/utils/filter-ecomm-events.ts, packages/google-analytics/src/utils/index.ts, packages/google-analytics/src/utils/remove-keys.ts
Checklist
----
What was done
----
Fixed (hopefully) this issue: https://stackoverflow.com/questions/56529876/how-to-get-multiple-trackers-to-work-using-redux-beacon-google-analytics
----
StackOverflow
:heart: Thanks
----
=> Omit extra keys when making hits

README.md
Add information about redux-dynamic-modules-beacon extension.
Checklist
----
What was done
----
Added documentation
----
- #341 
:heart: Thanks
----
=> Update README with redux-dynamic-modules-beacon info

packages/amplitude/src/event-helpers.ts
Checklist
----
What was done
----
- fixes typo that prevents users from being completely anonymized after an Amplitude logout
----
:heart: Thanks
----
=> Fixes Amplitude to regenerateDeviceId after logout
